api_login_check:
    path: /api/login_check
api_refresh_token:
    path: /api/token/refresh
homepage:
    path: /
    controller: App\Controller\DefaultController::index

App\Controller\:
    resource: '../src/Controller/'
    type: attribute

